name: Next.js EC2 Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::800309353239:role/GitHub_OIDC_role
          aws-region: ap-south-1

      - name: Trigger Deployment using AWS SSM
        run: |

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0a82bcf38a1cbdc0e" \
            --document-name "AWS-RunShellScript" \
            --comment "Next.js Deployment" \
            --parameters 'commands=[
              "set -e",
              "cd /opt/apps",
              "git config --global --add safe.directory /opt/apps",
              "echo ==================================",
              "echo Starting Deployment",
              "echo ==================================",
              "git pull origin main",
              "echo Installing Dependencies",
              "npm install",
              "echo Building Application",
              "npm run build",
              "echo Reloading PM2 Cluster",
              "pm2 reload ecosystem.config.js",
              "pm2 save",
              "echo Waiting for Application Startup",
              "sleep 15",
              "echo Running Health Check",
              "curl -f http://127.0.0.1:3000/api/health"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "=================================="
          echo "SSM Command Triggered"
          echo "=================================="

          echo "Command ID: $COMMAND_ID"

          STATUS="Pending"

          echo "Waiting for deployment completion..."

          while [ "$STATUS" = "Pending" ] || \
                [ "$STATUS" = "InProgress" ] || \
                [ "$STATUS" = "Delayed" ]
          do

            sleep 5

            STATUS=$(aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id "i-0a82bcf38a1cbdc0e" \
              --query "Status" \
              --output text)

            echo "Current Status: $STATUS"

          done

          echo "=================================="
          echo "Final Deployment Logs"
          echo "=================================="

          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id "i-0a82bcf38a1cbdc0e"

          if [ "$STATUS" != "Success" ]; then
            echo "=================================="
            echo "Deployment Failed"
            echo "=================================="
            exit 1
          fi

          echo "=================================="
          echo "Deployment Successful"
          echo "=================================="
